
name: GL-MT300N-V2 LEDE

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Space cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        df -h

    - name: Clone LEDE
      run: git clone https://github.com/coolsnowwolf/lede -b master

    - name: Load custom feeds
      run: |
        chmod +x ./diy-feeds.sh
        cd lede
        $GITHUB_WORKSPACE/diy-feeds.sh

    - name: Update feeds
      run: cd lede && scripts/feeds update -a

    - name: Install feeds
      run: cd lede && scripts/feeds install -a

    - name: Load custom config
      run: |
        cp .config lede/.config
        chmod +x diy-conf.sh
        cd lede
        $GITHUB_WORKSPACE/diy-conf.sh

    - name: Download packages
      run: |
        cd lede
        make defconfig
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile firmware
      run: |
        cd lede
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: lede_firmware
        path: ./lede/bin/targets/
